version: "3.8"
services:
  jekyll:
    image: gir21/devcontainer-jekyll:2.7.8
    volumes:
      # - ..:/srv/jekyll:cached
      - bundle-cache:/usr/local/bundle
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - JEKYLL_ENV=development
    ports:
      - "4000:4000"
      - "44004:44004" # LiveReload
    working_dir: /srv/jekyll

volumes:
  bundle-cache:
